"""changed the nullable to True in the profile image url column

Revision ID: 02286e6d909a
Revises: 1e3930ec89d9
Create Date: 2025-04-06 15:16:59.313955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02286e6d909a'
down_revision = '1e3930ec89d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
